### ISSUE TITLE
[Question]Can LC works with a premium paid cert?

### ISSUE THREAD

**Issue by michael1900** [hugeBlack/LiveContainer#22] opened 2024-12-26 10:18 UTC
### Describe the issue

Hi! Is it possible to use LC without SodeStore/AltStore but with a paid cert? 
I tried to sign with a paid cert and LC “works” but obviously apps in it like kodi in this case never run.
So can be possible make LC compatible/usable with paid cert? I mean mobile provisioning, p12 files, etc.. 
Thanks!

**Comment by hugeBlack** [comment] 2024-12-26 11:12
Duplicate of #64, #231. The author of #231 show interest in implementing this feature, but has no progress yet.

I personally won't implement this feature since I will never consider purchasing a paid cert.

Also, don't make feature requests in this repo.

**Closed as not planned by hugeBlack** 2024-12-26 11:12 UTC

**Comment by michael1900** [comment] 2024-12-26 16:21
> 
> Also, don't make feature requests in this repo.

I can't fully understand your replies sometimes. Where was I supposed to post this? I think that use LC with a paid cert would be the best combo and would eliminate the boring dependence on various stores and continuous refreshes. You don't always have wifi available, especially in vacation spots. Btw, thanks.

**Comment by hugeBlack** [comment] 2025-01-20 16:17
Personal cert support is implemented in the latest build (3.2.50) and you can have a try if you want. Some functions or apps will not work due to entitlement issues varying from cert to cert. I have only tested this feature on enterprise certs in Jailbroken environment, so I'm not sure if it also works well on personal (ah hoc) certs
